
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/marketingappdb
    username: root
    password: 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update          
  mvc:
    view:
      prefix: /WEB-INF/jsps/
      suffix: .jsp
      
# Configuring SMTP server:

  mail:
    host: smtp.gmail.com
    port: 587
    username: selauto2802@gmail.com
    password: atrukjpvnraqapmx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true